name: pushups_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  auto_route: ^4.0.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1

  flutter_localizations:
    sdk: flutter 
  freezed_annotation: ^2.0.1  
  i69n: ^2.1.0

  injectable: ^1.5.3
  shared_preferences: ^2.0.15

dev_dependencies:
  auto_route_generator: ^4.0.0
  bdd_widget_test: ^1.3.0
  build_runner:
  flutter_test:
    sdk: flutter
  freezed: ^2.0.2
  injectable_generator: ^1.5.3
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/pushups.jpeg

