name: pushups_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  auto_route: ^7.8.4
  bloc: ^8.1.2
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3

  flutter_localizations:
    sdk: flutter 
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  i69n: ^2.1.0
  injectable: ^2.3.2
  shared_preferences: ^2.2.2

dev_dependencies:
  auto_route_generator: ^7.3.2
  bdd_widget_test: ^1.6.1
  build_runner:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  injectable_generator: ^2.4.1
  mocktail: ^1.0.1
  very_good_analysis: ^3.0.2

flutter:
  uses-material-design: true
  assets:
   - assets/images/pushups.jpeg

